---
- name: Test ansible facts with Morpheus run.
  hosts: all
  gather_facts: yes
  tasks:   
    - debug:
        msg: "{{ morpheus['results']['resultTaskOne'] }}"
        msg: "{{ morpheus['instance']['name'] }}"
        msg: "{{ morpheus['results']['resultTaskTwo'] }}"