---
# tasks file for linux_partition
- name: "Create partition"
  community.general.parted:
    device: "/dev/sdb"
    number: 1
    label: "gpt"
    flags: lvm
    state: present
    part_end: "100%"